export const etfShareDetails = {
  ITDC: 'iShares® LifePath® Target Date 2035 ETF seeks to provide retirement outcomes through exposure to a broad portfolio of ETFs which adjusts its allocation as it approaches its target date.',
  ITDD: 'iShares® LifePath® Target Date 2040 ETF seeks to provide retirement outcomes through exposure to a broad portfolio of ETFs which adjusts its allocation as it approaches its target date.',
  ITDE: 'iShares® LifePath® Target Date 2045 ETF seeks to provide retirement outcomes through exposure to a broad portfolio of ETFs which adjusts its allocation as it approaches its target date.',
  IRTR: 'iShares® LifePath® Retirement ETF seeks to provide exposure to a conservative, broad portfolio of ETFs covering global asset classes.',
  ICSH: 'The BlackRock Ultra Short-Term Bond ETF seeks to provide current income consistent with preservation of capital.',
  NEAR: 'The BlackRock Short Duration Bond ETF seeks total return in excess of the reference benchmark.',
  MEAR: 'The BlackRock Short Maturity Municipal Bond ETF seeks to maximize tax-free current income.',
  HDV: 'The iShares Core High Dividend ETF seeks to track the investment results of an index composed of relatively high dividend paying U.S. equities.',
  DVY: 'The iShares Select Dividend ETF seeks to track the investment results of an index composed of relatively high dividend paying U.S. equities.',
  DGRO: 'The iShares Core Dividend Growth ETF seeks to track the investment results of an index composed of U.S. equities with a history of consistently growing dividends.',
  USHY: 'The iShares Broad USD High Yield Corporate Bond ETF seeks to track the investment results of an index composed of U.S. dollar-denominated, high yield corporate bonds.',
  TLTW: 'The iShares 20+ Year Treasury Bond BuyWrite Strategy ETF seeks to track the investment results of an index that reflects a strategy of holding the iShares 20+ Year Treasury Bond ETF while writing (selling) one-month covered call options to generate income.',
  BALI: 'The BlackRock Advantage Large Cap Income ETF seeks consistent income with lower volatility than the broader U.S. equity market.',
  USMV: 'The iShares MSCI USA Min Vol Factor ETF seeks to track the investment results of an index composed of U.S. equities that, in the aggregate, have lower volatility characteristics relative to the broader U.S. equity market.',
  EFAV: 'The iShares MSCI EAFE Min Vol Factor ETF seeks to track the investment results of an index composed of developed market equities that, in the aggregate, have lower volatility characteristics relative to the broader developed equity markets, excluding the U.S. and Canada.',
  EEMV: 'The iShares MSCI EAFE Min Vol Factor ETF seeks to track the investment results of an index composed of developed market equities that, in the aggregate, have lower volatility characteristics relative to the broader developed equity markets, excluding the U.S. and Canada.',
  IVVM: "iShares Large Cap Moderate Buffer ETF seeks to track the share price return of the iShares Core S&P 500 ETF (the 'Underlying ETF') up to an approximate upside limit, while seeking to provide downside protection against approximately the first 5% of Underlying ETF losses over each calendar quarter.",
  IVVB: 'iShares Large Cap Deep Buffer ETF seeks to track the share price return of the iShares Core S&P 500 ETF (the “Underlying ETF”) up to an approximate upside limit, while seeking to provide downside protection against approximately 5-20% of Underlying ETF losses over each calendar quarter.',
  TIP: 'The iShares TIPS Bond ETF seeks to track the investment results of an index composed of inflation-protected U.S. Treasury bonds.',
  STIP: 'The iShares 0-5 Year TIPS Bond ETF seeks to track the investment results of an index composed of inflation-protected U.S. Treasury bonds with remaining maturities of less than five years.',
  BRLN: 'The fund primarily seeks to provide high current income and secondarily seeks to provide long-term capital appreciation.',
  ITOT: 'The iShares Core S&P Total U.S. Stock Market ETF seeks to track the investment results of a broad-based index composed of U.S. equities.',
  IVV: 'The iShares Core S&P 500 ETF seeks to track the investment results of an index composed of large-capitalization U.S. equities.',
  IJH: 'The iShares Core S&P Mid-Cap ETF seeks to track the investment results of an index composed of mid-capitalization U.S. equities.',
  XT: 'The iShares Core S&P Mid-Cap ETF seeks to track the investment results of an index composed of mid-capitalization U.S. equities.',
  IHAK: 'The iShares Cybersecurity and Tech ETF seeks to track the investment results of an index composed of developed and emerging market companies involved in cyber security and technology, including cyber security hardware, software, products, and services.',
  IDNA: 'gfgfThe iShares Genomics Immunology and Healthcare ETF seeks to track the investment results of an index composed of developed and emerging market companies that could benefit from the long-term growth and innovation in genomics, immunology, and bioengineering.dg',
  LRGF: 'The iShares U.S. Equity Factor ETF seeks to track the investment results of an index composed of U.S. large- and mid-capitalization stocks that have favorable exposure to target style factors subject to constraints.',
  MTUM: 'The iShares MSCI USA Momentum Factor ETF seeks to track the investment results of an index composed of U.S. large- and mid-capitalization stocks exhibiting relatively higher price momentum.',
  QUAL: 'The iShares MSCI USA Momentum Factor ETF seeks to track the investment results of an index composed of U.S. large- and mid-capitalization stocks exhibiting relatively higher price momentum.',
};
